// frontend/src/pages/naive/NaiveFormModal.tsx
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Alert,
  Button,
  Col,
  DatePicker,
  Divider,
  Form,
  Input,
  InputNumber,
  Modal,
  Row,
  Select,
  Space,
  Switch,
  Tooltip,
  message,
} from 'antd';
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';

import { HttpUtil } from '@/utils';
import type { Msg } from '@/utils';
import type { NaivePayload, NaiveServer, NaiveUser } from './useNaive';
import './NaivePage.css';

const GB = 1024 * 1024 * 1024;

interface NaiveFormModalProps {
  open: boolean;
  mode: 'add' | 'edit';
  server: NaiveServer | null;
  save: (payload: NaivePayload) => Promise<Msg<unknown>>;
  onOpenChange: (open: boolean) => void;
}

function blank(): NaivePayload {
  return {
    remark: '',
    enable: false,
    subId: '',
    listen: '',
    port: 443,
    domain: '',
    useAcme: false,
    acmeEmail: '',
    certFile: '',
    keyFile: '',
    authUser: '',
    authPass: '',
    ipLimit: 0,
    padding: true,
    enableH3: true,
    logLevel: 'WARN',
    extraArgs: '',
    useRawConfig: false,
    rawConfig: '',
    total: 0,
    expiryTime: 0,
    trafficReset: 'never',
    users: [],
  };
}

function fromServer(server: NaiveServer): NaivePayload {
  const { id: _id, up: _up, down: _down, ...rest } = server;
  return { ...blank(), ...rest, users: (rest.users ?? []).map((u) => ({ ...u })) };
}

export default function NaiveFormModal({
  open,
  mode,
  server,
  save,
  onOpenChange,
}: NaiveFormModalProps) {
  const { t } = useTranslation();
  const [messageApi, messageContextHolder] = message.useMessage();
  // The page remounts this modal per open, so the initializer seeds the form.
  const [form, setForm] = useState<NaivePayload>(() => (server ? fromServer(server) : blank()));
  const [saving, setSaving] = useState(false);
  const [validating, setValidating] = useState(false);

  const set = <K extends keyof NaivePayload>(key: K, value: NaivePayload[K]) =>
    setForm((f) => ({ ...f, [key]: value }));

  const setUser = (idx: number, patch: Partial<NaiveUser>) =>
    setForm((f) => ({
      ...f,
      users: f.users.map((u, i) => (i === idx ? { ...u, ...patch } : u)),
    }));

  function validate(): string | null {
    const f = form;
    if (f.useRawConfig) {
      return f.rawConfig.trim() ? null : t('pages.naive.errRawEmpty');
    }
    if (!f.domain.trim()) return t('pages.naive.errDomain');
    if (!f.port || f.port < 1 || f.port > 65535) return t('pages.naive.errPort');
    if (!f.authUser.trim() || !f.authPass.trim()) return t('pages.naive.errAuth');
    if (f.useAcme) {
      if (!f.acmeEmail.trim()) return t('pages.naive.errAcmeEmail');
    } else if (!f.certFile.trim() || !f.keyFile.trim()) {
      return t('pages.naive.errCert');
    }
    return null;
  }

  // Fills the raw editor with the Caddyfile the panel would generate from the form.
  async function prefillRaw() {
    const msg = await HttpUtil.post<string>(
      '/panel/api/naive/preview',
      { ...form, useRawConfig: false },
      { silentSuccess: true },
    );
    if (msg?.success && msg.obj) set('rawConfig', msg.obj);
  }

  async function runValidate() {
    if (!form.rawConfig.trim()) {
      messageApi.warning(t('pages.naive.errRawEmpty'));
      return;
    }
    setValidating(true);
    try {
      const msg = await HttpUtil.post(
        '/panel/api/naive/validate',
        { text: form.rawConfig },
        { silent: true },
      );
      if (msg?.success) messageApi.success(t('pages.naive.rawValid'));
      else messageApi.error(msg?.msg || t('pages.naive.rawInvalid'));
    } finally {
      setValidating(false);
    }
  }

  function onToggleRaw(v: boolean) {
    set('useRawConfig', v);
    if (v && !form.rawConfig.trim()) void prefillRaw();
  }

  async function onOk() {
    const err = validate();
    if (err) {
      messageApi.error(err);
      return;
    }
    setSaving(true);
    try {
      const msg = await save(form);
      if (msg?.success) onOpenChange(false);
    } finally {
      setSaving(false);
    }
  }

  const totalGB = form.total > 0 ? +(form.total / GB).toFixed(2) : 0;

  return (
    <Modal
      open={open}
      title={mode === 'edit' ? t('pages.naive.editTitle') : t('pages.naive.addTitle')}
      confirmLoading={saving}
      okText={t('save')}
      cancelText={t('cancel')}
      width={640}
      onOk={onOk}
      onCancel={() => onOpenChange(false)}
      destroyOnHidden
    >
      {messageContextHolder}
      <Form layout="vertical">
        <Row gutter={12}>
          <Col xs={24} sm={12}>
            <Form.Item label={t('pages.naive.fields.remark')}>
              <Input value={form.remark} onChange={(e) => set('remark', e.target.value)} />
            </Form.Item>
          </Col>
          <Col xs={12} sm={6}>
            <Form.Item label={t('pages.naive.fields.enable')}>
              <Switch checked={form.enable} onChange={(v) => set('enable', v)} />
            </Form.Item>
          </Col>
          <Col xs={12} sm={6}>
            <Form.Item label={t('pages.naive.fields.advanced')}>
              <Switch checked={form.useRawConfig} onChange={onToggleRaw} />
            </Form.Item>
          </Col>
        </Row>

        <Form.Item label={t('pages.naive.fields.subId')} help={t('pages.naive.subIdHint')}>
          <Input
            value={form.subId}
            placeholder="my-subscription"
            onChange={(e) => set('subId', e.target.value)}
          />
        </Form.Item>

        {form.useRawConfig ? (
          <>
            <Alert
              type="info"
              showIcon
              title={t('pages.naive.rawHint')}
              style={{ marginBottom: 12 }}
            />
            <Form.Item label={t('pages.naive.fields.rawConfig')} required>
              <Input.TextArea
                className="naive-raw-editor"
                value={form.rawConfig}
                autoSize={{ minRows: 12, maxRows: 24 }}
                spellCheck={false}
                onChange={(e) => set('rawConfig', e.target.value)}
              />
            </Form.Item>
            <Space style={{ marginBottom: 12 }}>
              <Button loading={validating} onClick={runValidate}>
                {t('pages.naive.validate')}
              </Button>
              <Button onClick={prefillRaw}>{t('pages.naive.regenerate')}</Button>
            </Space>
          </>
        ) : (
          <>
            <Row gutter={12}>
              <Col xs={24} sm={14}>
                <Form.Item label={t('pages.naive.fields.domain')} required>
                  <Input
                    value={form.domain}
                    placeholder="example.com"
                    onChange={(e) => set('domain', e.target.value)}
                  />
                </Form.Item>
              </Col>
              <Col xs={12} sm={6}>
                <Form.Item label={t('pages.naive.fields.port')} required>
                  <InputNumber
                    value={form.port}
                    min={1}
                    max={65535}
                    style={{ width: '100%' }}
                    onChange={(v) => set('port', v ?? 0)}
                  />
                </Form.Item>
              </Col>
              <Col xs={12} sm={4}>
                <Form.Item label={t('pages.naive.fields.listen')}>
                  <Input
                    value={form.listen}
                    placeholder="all"
                    onChange={(e) => set('listen', e.target.value)}
                  />
                </Form.Item>
              </Col>
            </Row>

            <Row gutter={12}>
              <Col xs={24} sm={9}>
                <Form.Item label={t('pages.naive.fields.authUser')} required>
                  <Input value={form.authUser} onChange={(e) => set('authUser', e.target.value)} />
                </Form.Item>
              </Col>
              <Col xs={24} sm={9}>
                <Form.Item label={t('pages.naive.fields.authPass')} required>
                  <Input.Password
                    value={form.authPass}
                    onChange={(e) => set('authPass', e.target.value)}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} sm={6}>
                <Form.Item
                  label={t('pages.naive.fields.ipLimit')}
                  help={t('pages.naive.ipLimitHint')}
                >
                  <InputNumber
                    value={form.ipLimit}
                    min={0}
                    style={{ width: '100%' }}
                    placeholder={t('pages.naive.unlimited')}
                    onChange={(v) => set('ipLimit', v ?? 0)}
                  />
                </Form.Item>
              </Col>
            </Row>

            <Row gutter={12}>
              <Col xs={24} sm={10}>
                <Form.Item label={t('pages.naive.fields.useAcme')}>
                  <Switch checked={form.useAcme} onChange={(v) => set('useAcme', v)} />
                </Form.Item>
              </Col>
              {form.useAcme && (
                <Col xs={24} sm={14}>
                  <Form.Item label={t('pages.naive.fields.acmeEmail')} required>
                    <Input
                      value={form.acmeEmail}
                      placeholder="me@example.com"
                      onChange={(e) => set('acmeEmail', e.target.value)}
                    />
                  </Form.Item>
                </Col>
              )}
            </Row>

            {!form.useAcme && (
              <>
                <Form.Item label={t('pages.naive.fields.certFile')} required>
                  <Input
                    value={form.certFile}
                    placeholder="/etc/letsencrypt/live/example.com/fullchain.pem"
                    onChange={(e) => set('certFile', e.target.value)}
                  />
                </Form.Item>
                <Form.Item label={t('pages.naive.fields.keyFile')} required>
                  <Input
                    value={form.keyFile}
                    placeholder="/etc/letsencrypt/live/example.com/privkey.pem"
                    onChange={(e) => set('keyFile', e.target.value)}
                  />
                </Form.Item>
              </>
            )}

            <Row gutter={12}>
              <Col xs={12} sm={4}>
                <Form.Item label={t('pages.naive.fields.padding')}>
                  <Switch checked={form.padding} onChange={(v) => set('padding', v)} />
                </Form.Item>
              </Col>
              <Col xs={12} sm={4}>
                <Form.Item label={t('pages.naive.fields.enableH3')}>
                  <Switch checked={form.enableH3} onChange={(v) => set('enableH3', v)} />
                </Form.Item>
              </Col>
              <Col xs={24} sm={8}>
                <Form.Item label={t('pages.naive.fields.logLevel')}>
                  <Select
                    value={form.logLevel}
                    onChange={(v) => set('logLevel', v)}
                    options={['DEBUG', 'INFO', 'WARN', 'ERROR'].map((v) => ({
                      value: v,
                      label: v,
                    }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} sm={8}>
                <Form.Item label={t('pages.naive.fields.extraArgs')}>
                  <Input
                    value={form.extraArgs}
                    placeholder="--log-net-log=..."
                    onChange={(e) => set('extraArgs', e.target.value)}
                  />
                </Form.Item>
              </Col>
            </Row>

            <Row gutter={12}>
              <Col xs={24} sm={8}>
                <Form.Item label={t('pages.naive.fields.totalGB')}>
                  <InputNumber
                    value={totalGB}
                    min={0}
                    step={1}
                    style={{ width: '100%' }}
                    placeholder={t('pages.naive.unlimited')}
                    onChange={(v) => set('total', v && v > 0 ? Math.round(v * GB) : 0)}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} sm={8}>
                <Form.Item label={t('pages.naive.fields.expiryTime')}>
                  <DatePicker
                    showTime
                    style={{ width: '100%' }}
                    placeholder={t('pages.naive.never')}
                    value={form.expiryTime > 0 ? dayjs(form.expiryTime) : null}
                    onChange={(v) => set('expiryTime', v ? v.valueOf() : 0)}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} sm={8}>
                <Form.Item label={t('pages.naive.fields.trafficReset')}>
                  <Select
                    value={form.trafficReset}
                    onChange={(v) => set('trafficReset', v)}
                    options={[
                      { value: 'never', label: t('pages.naive.reset.never') },
                      { value: 'day', label: t('pages.naive.reset.day') },
                      { value: 'week', label: t('pages.naive.reset.week') },
                      { value: 'month', label: t('pages.naive.reset.month') },
                    ]}
                  />
                </Form.Item>
              </Col>
            </Row>

            <Divider style={{ margin: '4px 0 12px' }}>{t('pages.naive.usersSection')}</Divider>
            <div className="naive-users">
              {form.users.map((u, idx) => (
                <div key={u.id ?? `new-${idx}`} className="naive-user-row">
                  <Input
                    value={u.username}
                    placeholder={t('pages.naive.fields.authUser')}
                    onChange={(e) => setUser(idx, { username: e.target.value })}
                  />
                  <Input.Password
                    value={u.password}
                    placeholder={t('pages.naive.fields.authPass')}
                    onChange={(e) => setUser(idx, { password: e.target.value })}
                  />
                  <Tooltip title={t('pages.naive.fields.enable')}>
                    <Switch checked={u.enable} onChange={(v) => setUser(idx, { enable: v })} />
                  </Tooltip>
                  <Button
                    danger
                    type="text"
                    icon={<DeleteOutlined />}
                    onClick={() =>
                      setForm((f) => ({ ...f, users: f.users.filter((_, i) => i !== idx) }))
                    }
                  />
                </div>
              ))}
              <Button
                type="dashed"
                block
                icon={<PlusOutlined />}
                onClick={() =>
                  setForm((f) => ({
                    ...f,
                    users: [...f.users, { username: '', password: '', enable: true }],
                  }))
                }
              >
                {t('pages.naive.addUser')}
              </Button>
            </div>
          </>
        )}
      </Form>
    </Modal>
  );
}

// frontend/src/pages/naive/NaiveFormModal.vue
<script setup>
import { computed, ref, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { message } from 'ant-design-vue';
import dayjs from 'dayjs';
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons-vue';
import { HttpUtil } from '@/utils';

const props = defineProps({
  open: { type: Boolean, default: false },
  mode: { type: String, default: 'add' },
  server: { type: Object, default: null },
});
const emit = defineEmits(['update:open', 'save']);

const { t } = useI18n();

function blank() {
  return {
    remark: '',
    enable: false,
    subId: '',
    listen: '',
    port: 443,
    domain: '',
    useAcme: false,
    acmeEmail: '',
    certFile: '',
    keyFile: '',
    authUser: '',
    authPass: '',
    ipLimit: 0,
    padding: true,
    enableH3: true,
    logLevel: 'WARN',
    extraArgs: '',
    useRawConfig: false,
    rawConfig: '',
    total: 0,
    expiryTime: 0,
    trafficReset: 'never',
    users: [],
  };
}

const form = ref(blank());
const saving = ref(false);

function addUser() {
  if (!Array.isArray(form.value.users)) form.value.users = [];
  form.value.users.push({ username: '', password: '', enable: true });
}

function removeUser(idx) {
  form.value.users.splice(idx, 1);
}

const GB = 1024 * 1024 * 1024;

// Quota is stored in bytes but entered in GB. 0 = unlimited.
const totalGB = computed({
  get: () => (form.value.total > 0 ? +(form.value.total / GB).toFixed(2) : 0),
  set: (v) => { form.value.total = v > 0 ? Math.round(v * GB) : 0; },
});

// Expiry is stored as an absolute ms timestamp but edited as a date.
// 0 = never.
const expiryDate = computed({
  get: () => (form.value.expiryTime > 0 ? dayjs(form.value.expiryTime) : null),
  set: (v) => { form.value.expiryTime = v ? v.valueOf() : 0; },
});

watch(
  () => props.open,
  (v) => {
    if (v) form.value = props.server ? { ...blank(), ...props.server } : blank();
  },
);

const title = computed(() =>
  props.mode === 'edit' ? t('pages.naive.editTitle') : t('pages.naive.addTitle'),
);

function close() {
  emit('update:open', false);
}

function validate() {
  const f = form.value;
  if (f.useRawConfig) {
    if (!f.rawConfig.trim()) return t('pages.naive.errRawEmpty');
    return null;
  }
  if (!f.domain.trim()) return t('pages.naive.errDomain');
  if (!f.port || f.port < 1 || f.port > 65535) return t('pages.naive.errPort');
  if (!f.authUser.trim() || !f.authPass.trim()) return t('pages.naive.errAuth');
  if (f.useAcme) {
    if (!f.acmeEmail.trim()) return t('pages.naive.errAcmeEmail');
  } else if (!f.certFile.trim() || !f.keyFile.trim()) {
    return t('pages.naive.errCert');
  }
  return null;
}

// fill the raw editor with the Caddyfile we'd generate from the current form
async function prefillRaw() {
  const msg = await HttpUtil.post('/panel/api/naive/preview', { ...form.value, useRawConfig: false });
  if (msg?.success && msg.obj) {
    form.value.rawConfig = msg.obj;
  }
}

const validating = ref(false);
async function runValidate() {
  if (!form.value.rawConfig.trim()) {
    message.warning(t('pages.naive.errRawEmpty'));
    return;
  }
  validating.value = true;
  try {
    const msg = await HttpUtil.post('/panel/api/naive/validate', { text: form.value.rawConfig });
    if (msg?.success) message.success(t('pages.naive.rawValid'));
    else message.error(msg?.msg || t('pages.naive.rawInvalid'));
  } finally {
    validating.value = false;
  }
}

function onToggleRaw(v) {
  form.value.useRawConfig = v;
  if (v && !form.value.rawConfig.trim()) prefillRaw();
}

async function save() {
  const err = validate();
  if (err) {
    message.error(err);
    return;
  }
  saving.value = true;
  try {
    const msg = await emit('save', { ...form.value });
    if (msg && msg.then) await msg;
    close();
  } finally {
    saving.value = false;
  }
}
</script>

<template>
  <a-modal
    :open="open"
    :title="title"
    :confirm-loading="saving"
    :ok-text="t('save')"
    :cancel-text="t('cancel')"
    width="640px"
    @ok="save"
    @cancel="close"
  >
    <a-form layout="vertical">
      <a-row :gutter="12">
        <a-col :span="12">
          <a-form-item :label="t('pages.naive.fields.remark')">
            <a-input v-model:value="form.remark" />
          </a-form-item>
        </a-col>
        <a-col :span="6">
          <a-form-item :label="t('pages.naive.fields.enable')">
            <a-switch v-model:checked="form.enable" />
          </a-form-item>
        </a-col>
        <a-col :span="6">
          <a-form-item :label="t('pages.naive.fields.advanced')">
            <a-switch
              :checked="form.useRawConfig"
              @change="onToggleRaw"
            />
          </a-form-item>
        </a-col>
      </a-row>

      <a-row :gutter="12">
        <a-col :span="24">
          <a-form-item :label="t('pages.naive.fields.subId')" :help="t('pages.naive.subIdHint')">
            <a-input v-model:value="form.subId" placeholder="my-subscription" />
          </a-form-item>
        </a-col>
      </a-row>

      <!-- Advanced (raw Caddyfile) mode -->
      <template v-if="form.useRawConfig">
        <a-alert
          type="info"
          show-icon
          :message="t('pages.naive.rawHint')"
          style="margin-bottom: 12px;"
        />
        <a-form-item :label="t('pages.naive.fields.rawConfig')" required>
          <a-textarea
            v-model:value="form.rawConfig"
            :auto-size="{ minRows: 12, maxRows: 24 }"
            class="raw-editor"
            spellcheck="false"
          />
        </a-form-item>
        <a-space style="margin-bottom: 12px;">
          <a-button :loading="validating" @click="runValidate">{{ t('pages.naive.validate') }}</a-button>
          <a-button @click="prefillRaw">{{ t('pages.naive.regenerate') }}</a-button>
        </a-space>
      </template>

      <!-- Simple form mode -->
      <template v-else>

      <a-row :gutter="12">
        <a-col :span="14">
          <a-form-item :label="t('pages.naive.fields.domain')" required>
            <a-input v-model:value="form.domain" placeholder="example.com" />
          </a-form-item>
        </a-col>
        <a-col :span="6">
          <a-form-item :label="t('pages.naive.fields.port')" required>
            <a-input-number v-model:value="form.port" :min="1" :max="65535" style="width: 100%" />
          </a-form-item>
        </a-col>
        <a-col :span="4">
          <a-form-item :label="t('pages.naive.fields.listen')">
            <a-input v-model:value="form.listen" placeholder="all" />
          </a-form-item>
        </a-col>
      </a-row>

      <a-row :gutter="12">
        <a-col :span="9">
          <a-form-item :label="t('pages.naive.fields.authUser')" required>
            <a-input v-model:value="form.authUser" />
          </a-form-item>
        </a-col>
        <a-col :span="9">
          <a-form-item :label="t('pages.naive.fields.authPass')" required>
            <a-input-password v-model:value="form.authPass" />
          </a-form-item>
        </a-col>
        <a-col :span="6">
          <a-form-item :label="t('pages.naive.fields.ipLimit')" :help="t('pages.naive.ipLimitHint')">
            <a-input-number v-model:value="form.ipLimit" :min="0" style="width: 100%"
              :placeholder="t('pages.naive.unlimited')" />
          </a-form-item>
        </a-col>
      </a-row>

      <a-row :gutter="12">
        <a-col :span="10">
          <a-form-item :label="t('pages.naive.fields.useAcme')">
            <a-switch v-model:checked="form.useAcme" />
          </a-form-item>
        </a-col>
        <a-col :span="14">
          <a-form-item v-if="form.useAcme" :label="t('pages.naive.fields.acmeEmail')" required>
            <a-input v-model:value="form.acmeEmail" placeholder="me@example.com" />
          </a-form-item>
        </a-col>
      </a-row>

      <template v-if="!form.useAcme">
        <a-form-item :label="t('pages.naive.fields.certFile')" required>
          <a-input v-model:value="form.certFile" placeholder="/etc/letsencrypt/live/example.com/fullchain.pem" />
        </a-form-item>
        <a-form-item :label="t('pages.naive.fields.keyFile')" required>
          <a-input v-model:value="form.keyFile" placeholder="/etc/letsencrypt/live/example.com/privkey.pem" />
        </a-form-item>
      </template>

      <a-row :gutter="12">
        <a-col :span="4">
          <a-form-item :label="t('pages.naive.fields.padding')">
            <a-switch v-model:checked="form.padding" />
          </a-form-item>
        </a-col>
        <a-col :span="4">
          <a-form-item :label="t('pages.naive.fields.enableH3')">
            <a-switch v-model:checked="form.enableH3" />
          </a-form-item>
        </a-col>
        <a-col :span="8">
          <a-form-item :label="t('pages.naive.fields.logLevel')">
            <a-select v-model:value="form.logLevel">
              <a-select-option value="DEBUG">DEBUG</a-select-option>
              <a-select-option value="INFO">INFO</a-select-option>
              <a-select-option value="WARN">WARN</a-select-option>
              <a-select-option value="ERROR">ERROR</a-select-option>
            </a-select>
          </a-form-item>
        </a-col>
        <a-col :span="8">
          <a-form-item :label="t('pages.naive.fields.extraArgs')">
            <a-input v-model:value="form.extraArgs" placeholder="--log-net-log=..." />
          </a-form-item>
        </a-col>
      </a-row>

      <a-row :gutter="12">
        <a-col :span="8">
          <a-form-item :label="t('pages.naive.fields.totalGB')">
            <a-input-number v-model:value="totalGB" :min="0" :step="1" style="width: 100%"
              :placeholder="t('pages.naive.unlimited')" />
          </a-form-item>
        </a-col>
        <a-col :span="8">
          <a-form-item :label="t('pages.naive.fields.expiryTime')">
            <a-date-picker v-model:value="expiryDate" show-time style="width: 100%"
              :placeholder="t('pages.naive.never')" />
          </a-form-item>
        </a-col>
        <a-col :span="8">
          <a-form-item :label="t('pages.naive.fields.trafficReset')">
            <a-select v-model:value="form.trafficReset">
              <a-select-option value="never">{{ t('pages.naive.reset.never') }}</a-select-option>
              <a-select-option value="day">{{ t('pages.naive.reset.day') }}</a-select-option>
              <a-select-option value="week">{{ t('pages.naive.reset.week') }}</a-select-option>
              <a-select-option value="month">{{ t('pages.naive.reset.month') }}</a-select-option>
            </a-select>
          </a-form-item>
        </a-col>
      </a-row>

      <a-divider style="margin: 4px 0 12px">{{ t('pages.naive.usersSection') }}</a-divider>
      <div class="naive-users">
        <div v-for="(u, idx) in form.users" :key="idx" class="naive-user-row">
          <a-input v-model:value="u.username" :placeholder="t('pages.naive.fields.authUser')" style="flex: 1" />
          <a-input-password v-model:value="u.password" :placeholder="t('pages.naive.fields.authPass')" style="flex: 1" />
          <a-tooltip :title="t('pages.naive.fields.enable')">
            <a-switch v-model:checked="u.enable" />
          </a-tooltip>
          <a-button danger type="text" @click="removeUser(idx)">
            <template #icon><DeleteOutlined /></template>
          </a-button>
        </div>
        <a-button type="dashed" block @click="addUser">
          <template #icon><PlusOutlined /></template>
          {{ t('pages.naive.addUser') }}
        </a-button>
      </div>
      </template>
    </a-form>
  </a-modal>
</template>

<style scoped>
.raw-editor :deep(textarea) {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 12px;
  tab-size: 4;
}

.naive-users {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.naive-user-row {
  display: flex;
  align-items: center;
  gap: 8px;
}
</style>
