// frontend/src/pages/naive/NaivePage.tsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Alert,
  Button,
  Card,
  Col,
  ConfigProvider,
  Empty,
  Layout,
  Modal,
  Result,
  Row,
  Space,
  Spin,
  Statistic,
  Table,
  Tag,
  Tooltip,
  message,
} from 'antd';
import type { ColumnsType } from 'antd/es/table';
import {
  CheckCircleOutlined,
  CloseCircleOutlined,
  CloudServerOutlined,
  CopyOutlined,
  DeleteOutlined,
  EditOutlined,
  FileTextOutlined,
  PauseCircleOutlined,
  PlayCircleOutlined,
  PlusOutlined,
  QrcodeOutlined,
  ReloadOutlined,
  UndoOutlined,
} from '@ant-design/icons';

import { useTheme } from '@/hooks/useTheme';
import { useMediaQuery } from '@/hooks/useMediaQuery';
import AppSidebar from '@/layouts/AppSidebar';
import { ClipboardManager, SizeFormatter } from '@/utils';
import { setMessageInstance } from '@/utils/messageBus';
import { QrPanel } from '@/pages/inbounds/qr';
import NaiveFormModal from './NaiveFormModal';
import { useNaive } from './useNaive';
import type { NaivePayload, NaiveServer, NaiveStatus } from './useNaive';
import './NaivePage.css';

function urlFor(s: NaiveServer, user: string, pass: string) {
  return `naive+https://${encodeURIComponent(user)}:${encodeURIComponent(pass)}@${s.domain}:${s.port}`;
}

// The primary credential plus every enabled extra user, each its own URL / QR.
function credsFor(s: NaiveServer) {
  const list = [{ label: s.authUser, url: urlFor(s, s.authUser, s.authPass) }];
  for (const u of s.users || []) {
    if (u.enable && u.username)
      list.push({ label: u.username, url: urlFor(s, u.username, u.password) });
  }
  return list;
}

const nameOf = (s: NaiveServer | null) => (s ? s.remark || `naive-${s.id}` : '');
const isDepleted = (s: NaiveServer) => s.total > 0 && (s.up || 0) + (s.down || 0) >= s.total;
const isExpired = (s: NaiveServer) => s.expiryTime > 0 && Date.now() >= s.expiryTime;

export default function NaivePage() {
  const { t } = useTranslation();
  const { isDark, isUltra, antdThemeConfig } = useTheme();
  const { isMobile } = useMediaQuery();
  const [modal, modalContextHolder] = Modal.useModal();
  const [messageApi, messageContextHolder] = message.useMessage();
  useEffect(() => {
    setMessageInstance(messageApi);
  }, [messageApi]);

  const {
    servers,
    statuses,
    loading,
    fetched,
    fetchError,
    caddy,
    refresh,
    installCaddy,
    fetchLog,
    create,
    update,
    remove,
    start,
    stop,
    restart,
    resetTraffic,
  } = useNaive();

  const [installing, setInstalling] = useState(false);
  const [installLog, setInstallLog] = useState('');
  const [formOpen, setFormOpen] = useState(false);
  const [formKey, setFormKey] = useState(0);
  const [formServer, setFormServer] = useState<NaiveServer | null>(null);
  const [logTarget, setLogTarget] = useState<NaiveServer | null>(null);
  const [logText, setLogText] = useState('');
  const [logLoading, setLogLoading] = useState(false);
  const [qrTarget, setQrTarget] = useState<NaiveServer | null>(null);

  const onInstallCaddy = useCallback(async () => {
    setInstalling(true);
    setInstallLog('');
    try {
      const res = await installCaddy((chunk) => setInstallLog((prev) => prev + chunk + '\n'));
      if (res.ok) messageApi.success(t('pages.naive.toasts.caddyInstalled'));
      else messageApi.error(res.err || t('pages.naive.toasts.caddyInstallFailed'));
    } catch (e) {
      messageApi.error(e instanceof Error ? e.message : String(e));
    } finally {
      setInstalling(false);
    }
  }, [installCaddy, messageApi, t]);

  const onAdd = useCallback(() => {
    setFormServer(null);
    setFormKey((k) => k + 1);
    setFormOpen(true);
  }, []);

  const onEdit = useCallback((s: NaiveServer) => {
    setFormServer({ ...s });
    setFormKey((k) => k + 1);
    setFormOpen(true);
  }, []);

  const onSave = useCallback(
    (payload: NaivePayload) => (formServer?.id ? update(formServer.id, payload) : create(payload)),
    [formServer, update, create],
  );

  const onDelete = useCallback(
    (s: NaiveServer) => {
      modal.confirm({
        title: t('pages.naive.deleteConfirmTitle', { name: s.remark || s.domain }),
        okText: t('delete'),
        okType: 'danger',
        cancelText: t('cancel'),
        onOk: async () => {
          const msg = await remove(s.id);
          if (msg?.success) messageApi.success(t('pages.naive.toasts.deleted'));
        },
      });
    },
    [modal, t, remove, messageApi],
  );

  const runAction = useCallback(
    async (fn: (id: number) => Promise<{ success: boolean }>, s: NaiveServer, toastKey: string) => {
      const msg = await fn(s.id);
      if (msg?.success) messageApi.success(t(toastKey));
    },
    [messageApi, t],
  );

  const loadLog = useCallback(
    async (s: NaiveServer) => {
      setLogLoading(true);
      try {
        const res = await fetchLog(s.id, 200);
        setLogText(res?.success ? res.obj || '' : res?.msg || t('pages.naive.logError'));
      } finally {
        setLogLoading(false);
      }
    },
    [fetchLog, t],
  );

  const onShowLog = useCallback(
    (s: NaiveServer) => {
      setLogTarget(s);
      setLogText('');
      void loadLog(s);
    },
    [loadLog],
  );

  const onCopy = useCallback(
    async (s: NaiveServer) => {
      if (await ClipboardManager.copyText(urlFor(s, s.authUser, s.authPass))) {
        messageApi.success(t('copied'));
      }
    },
    [messageApi, t],
  );

  const totals = useMemo(() => {
    const running = servers.filter((s) => statuses[s.id]?.running).length;
    return { total: servers.length, running, stopped: Math.max(0, servers.length - running) };
  }, [servers, statuses]);

  const statusTags = useCallback(
    (s: NaiveServer): ReactNode => {
      const st: NaiveStatus | undefined = statuses[s.id];
      let state: ReactNode;
      if (st?.running && st.listening && st.responding) {
        state = <Tag color="success">{t('pages.naive.running')}</Tag>;
      } else if (st?.running && st.listening) {
        state = <Tag color="warning">{t('pages.naive.unresponsive')}</Tag>;
      } else if (st?.running) {
        state = <Tag color="processing">{t('pages.naive.starting')}</Tag>;
      } else {
        state = <Tag>{t('pages.naive.stopped')}</Tag>;
      }
      return (
        <>
          {state}
          {isExpired(s) ? (
            <Tag color="error">{t('pages.naive.expired')}</Tag>
          ) : isDepleted(s) ? (
            <Tag color="error">{t('pages.naive.depleted')}</Tag>
          ) : null}
        </>
      );
    },
    [statuses, t],
  );

  const enableTag = useCallback(
    (s: NaiveServer) => (
      <Tag color={s.enable ? 'green' : 'default'}>
        {s.enable ? t('pages.naive.enabled') : t('pages.naive.disabled')}
      </Tag>
    ),
    [t],
  );

  const actions = useCallback(
    (s: NaiveServer, compact: boolean) => {
      const running = !!statuses[s.id]?.running;
      return (
        <Space size={compact ? 6 : 4} wrap className={compact ? 'naive-srv-actions' : undefined}>
          <Tooltip title={t('pages.naive.copyUrl')}>
            <Button size="small" icon={<CopyOutlined />} onClick={() => onCopy(s)} />
          </Tooltip>
          <Tooltip title={t('pages.naive.showQr')}>
            <Button size="small" icon={<QrcodeOutlined />} onClick={() => setQrTarget(s)} />
          </Tooltip>
          {running ? (
            <Button
              size="small"
              danger
              icon={<PauseCircleOutlined />}
              onClick={() => runAction(stop, s, 'pages.naive.toasts.stopped')}
            >
              {t('pages.naive.stop')}
            </Button>
          ) : (
            <Button
              size="small"
              type="primary"
              icon={<PlayCircleOutlined />}
              onClick={() => runAction(start, s, 'pages.naive.toasts.started')}
            >
              {t('pages.naive.start')}
            </Button>
          )}
          <Tooltip title={t('pages.naive.restart')}>
            <Button
              size="small"
              disabled={!running}
              icon={<ReloadOutlined />}
              onClick={() => runAction(restart, s, 'pages.naive.toasts.restarted')}
            />
          </Tooltip>
          <Tooltip title={t('pages.naive.viewLog')}>
            <Button size="small" icon={<FileTextOutlined />} onClick={() => onShowLog(s)} />
          </Tooltip>
          <Button size="small" icon={<EditOutlined />} onClick={() => onEdit(s)} />
          <Tooltip title={t('pages.naive.resetTraffic')}>
            <Button
              size="small"
              icon={<UndoOutlined />}
              onClick={() => runAction(resetTraffic, s, 'pages.naive.toasts.trafficReset')}
            />
          </Tooltip>
          <Button size="small" danger icon={<DeleteOutlined />} onClick={() => onDelete(s)} />
        </Space>
      );
    },
    [
      statuses,
      t,
      onCopy,
      runAction,
      stop,
      start,
      restart,
      resetTraffic,
      onShowLog,
      onEdit,
      onDelete,
    ],
  );

  const columns = useMemo<ColumnsType<NaiveServer>>(
    () => [
      { key: 'remark', title: t('pages.naive.fields.remark'), render: (_v, r) => nameOf(r) },
      {
        key: 'domain',
        title: t('pages.naive.fields.domain'),
        render: (_v, r) => (
          <code>
            {r.domain}:{r.port}
          </code>
        ),
      },
      {
        key: 'enable',
        title: t('pages.naive.fields.enable'),
        width: 110,
        render: (_v, r) => enableTag(r),
      },
      {
        key: 'status',
        title: t('pages.naive.statusCol'),
        width: 160,
        render: (_v, r) => statusTags(r),
      },
      {
        key: 'traffic',
        title: t('pages.naive.trafficCol'),
        width: 170,
        render: (_v, r) => (
          <Tooltip title={t('pages.naive.trafficHint')}>
            <span>
              ↑ {SizeFormatter.sizeFormat(r.up || 0)} / ↓ {SizeFormatter.sizeFormat(r.down || 0)}
            </span>
          </Tooltip>
        ),
      },
      {
        key: 'actions',
        title: '',
        width: 340,
        align: 'right',
        render: (_v, r) => actions(r, false),
      },
    ],
    [t, enableTag, statusTags, actions],
  );

  const pageClass = ['naive-page', isDark && 'is-dark', isUltra && 'is-ultra']
    .filter(Boolean)
    .join(' ');

  return (
    <ConfigProvider theme={antdThemeConfig}>
      {messageContextHolder}
      {modalContextHolder}
      <Layout className={pageClass}>
        <AppSidebar />

        <Layout className="content-shell">
          <Layout.Content id="content-layout" className="content-area">
            <Spin spinning={!fetched} delay={200} description={t('loading')} size="large">
              {!fetched ? (
                <div className="loading-spacer" />
              ) : fetchError ? (
                <Result
                  status="error"
                  title={t('somethingWentWrong')}
                  subTitle={fetchError}
                  extra={
                    <Button type="primary" loading={loading} onClick={() => refresh()}>
                      {t('refresh')}
                    </Button>
                  }
                />
              ) : (
                <Row gutter={[isMobile ? 8 : 16, isMobile ? 8 : 12]}>
                  {!caddy.installed && (
                    <Col span={24}>
                      <Alert
                        type="warning"
                        showIcon
                        title={t('pages.naive.caddy.missingTitle')}
                        description={
                          caddy.goPresent
                            ? t('pages.naive.caddy.canInstall')
                            : t('pages.naive.caddy.noGo')
                        }
                        action={
                          caddy.goPresent ? (
                            <Button
                              size="small"
                              type="primary"
                              loading={installing}
                              onClick={onInstallCaddy}
                            >
                              {installing
                                ? t('pages.naive.caddy.installing')
                                : t('pages.naive.caddy.install')}
                            </Button>
                          ) : undefined
                        }
                      />
                    </Col>
                  )}
                  {(installing || installLog) && (
                    <Col span={24}>
                      <Card size="small">
                        <pre className="naive-install-log">{installLog || '...'}</pre>
                      </Card>
                    </Col>
                  )}
                  {caddy.installed && (
                    <Col span={24}>
                      <Alert
                        type="success"
                        showIcon
                        closable
                        title={t('pages.naive.caddy.installedTitle', { v: caddy.version || '?' })}
                        description={`${caddy.source}: ${caddy.path}`}
                      />
                    </Col>
                  )}

                  <Col span={24}>
                    <Card size="small" hoverable className="summary-card">
                      <Row gutter={[16, isMobile ? 16 : 12]}>
                        <Col span={8}>
                          <Statistic
                            title={t('pages.naive.totals.total')}
                            value={String(totals.total)}
                            prefix={<CloudServerOutlined />}
                          />
                        </Col>
                        <Col span={8}>
                          <Statistic
                            title={t('pages.naive.totals.running')}
                            value={String(totals.running)}
                            prefix={
                              <CheckCircleOutlined style={{ color: 'var(--ant-color-success)' }} />
                            }
                          />
                        </Col>
                        <Col span={8}>
                          <Statistic
                            title={t('pages.naive.totals.stopped')}
                            value={String(totals.stopped)}
                            prefix={
                              <CloseCircleOutlined style={{ color: 'var(--ant-color-error)' }} />
                            }
                          />
                        </Col>
                      </Row>
                    </Card>
                  </Col>

                  <Col span={24}>
                    <Card
                      size="small"
                      hoverable
                      className="list-card"
                      title={t('pages.naive.title')}
                      extra={
                        <Space>
                          <Button
                            icon={<ReloadOutlined />}
                            loading={loading}
                            onClick={() => refresh()}
                          >
                            {t('refresh')}
                          </Button>
                          <Button type="primary" icon={<PlusOutlined />} onClick={onAdd}>
                            {t('pages.naive.add')}
                          </Button>
                        </Space>
                      }
                    >
                      {isMobile ? (
                        <div className="naive-mobile-cards">
                          {servers.length === 0 && <Empty description={t('pages.naive.empty')} />}
                          {servers.map((srv) => (
                            <div key={srv.id} className="naive-srv-card">
                              <div className="naive-srv-head">
                                <div className="naive-srv-title">{nameOf(srv)}</div>
                                {statusTags(srv)}
                              </div>
                              <div className="naive-srv-row">
                                <span className="naive-srv-label">
                                  {t('pages.naive.fields.domain')}
                                </span>
                                <code>
                                  {srv.domain}:{srv.port}
                                </code>
                              </div>
                              <div className="naive-srv-row">
                                <span className="naive-srv-label">
                                  {t('pages.naive.fields.enable')}
                                </span>
                                {enableTag(srv)}
                              </div>
                              {actions(srv, true)}
                            </div>
                          ))}
                        </div>
                      ) : (
                        <Table<NaiveServer>
                          columns={columns}
                          dataSource={servers}
                          pagination={false}
                          rowKey="id"
                          size="middle"
                          scroll={{ x: 'max-content' }}
                          locale={{ emptyText: <Empty description={t('pages.naive.empty')} /> }}
                        />
                      )}
                    </Card>
                  </Col>
                </Row>
              )}
            </Spin>
          </Layout.Content>
        </Layout>

        <NaiveFormModal
          key={formKey}
          open={formOpen}
          mode={formServer ? 'edit' : 'add'}
          server={formServer}
          save={onSave}
          onOpenChange={setFormOpen}
        />

        <Modal
          open={!!logTarget}
          title={t('pages.naive.logTitle', { name: nameOf(logTarget) })}
          width={780}
          footer={null}
          onCancel={() => setLogTarget(null)}
          destroyOnHidden
        >
          <Space style={{ marginBottom: 8 }}>
            <Button
              size="small"
              icon={<ReloadOutlined />}
              loading={logLoading}
              onClick={() => logTarget && loadLog(logTarget)}
            >
              {t('refresh')}
            </Button>
            <span className="naive-log-hint">{t('pages.naive.logHint')}</span>
          </Space>
          <pre className="naive-log-view">{logText || t('pages.naive.logEmpty')}</pre>
        </Modal>

        <Modal
          open={!!qrTarget}
          title={t('pages.naive.qrTitle', { name: nameOf(qrTarget) })}
          width={420}
          footer={null}
          onCancel={() => setQrTarget(null)}
          destroyOnHidden
        >
          {qrTarget &&
            credsFor(qrTarget).map((cred) => (
              <QrPanel key={cred.label} value={cred.url} remark={cred.label} />
            ))}
        </Modal>
      </Layout>
    </ConfigProvider>
  );
}

// frontend/src/pages/naive/NaivePage.vue
<script setup>
import { computed, ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { Modal, message } from 'ant-design-vue';
import {
  PlusOutlined,
  PlayCircleOutlined,
  PauseCircleOutlined,
  ReloadOutlined,
  EditOutlined,
  FileTextOutlined,
  DeleteOutlined,
  CopyOutlined,
  QrcodeOutlined,
  CloudServerOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
} from '@ant-design/icons-vue';

import { theme as themeState, antdThemeConfig } from '@/composables/useTheme.js';
import { useMediaQuery } from '@/composables/useMediaQuery.js';
import { ClipboardManager, SizeFormatter } from '@/utils';
import AppSidebar from '@/components/AppSidebar.vue';
import CustomStatistic from '@/components/CustomStatistic.vue';
import NaiveFormModal from './NaiveFormModal.vue';
import QrPanel from '../inbounds/QrPanel.vue';
import { useNaive } from './useNaive.js';

const { t } = useI18n();

const {
  servers,
  statuses,
  loading,
  fetched,
  caddy,
  refresh,
  installCaddy,
  fetchLog,
  create,
  update,
  remove,
  start,
  stop,
  restart,
  resetTraffic,
} = useNaive();

const installing = ref(false);
const installLog = ref('');
async function onInstallCaddy() {
  installing.value = true;
  installLog.value = '';
  try {
    const res = await installCaddy((chunk) => { installLog.value += chunk + '\n'; });
    if (res.ok) message.success(t('pages.naive.toasts.caddyInstalled'));
    else message.error(res.err || t('pages.naive.toasts.caddyInstallFailed'));
  } catch (e) {
    message.error(String(e?.message || e));
  } finally {
    installing.value = false;
  }
}

const { isMobile } = useMediaQuery();

const basePath = window.X_UI_BASE_PATH || '';
const requestUri = window.location.pathname;

const formOpen = ref(false);
const formMode = ref('add');
const formServer = ref(null);

function onAdd() {
  formMode.value = 'add';
  formServer.value = null;
  formOpen.value = true;
}

function onEdit(s) {
  formMode.value = 'edit';
  formServer.value = { ...s };
  formOpen.value = true;
}

async function onSave(payload) {
  if (formMode.value === 'edit' && formServer.value?.id) {
    return update(formServer.value.id, payload);
  }
  return create(payload);
}

function onDelete(s) {
  Modal.confirm({
    title: t('pages.naive.deleteConfirmTitle', { name: s.remark || s.domain }),
    okText: t('delete'),
    okType: 'danger',
    cancelText: t('cancel'),
    onOk: async () => {
      const msg = await remove(s.id);
      if (msg?.success) message.success(t('pages.naive.toasts.deleted'));
    },
  });
}

async function onStart(s) {
  const msg = await start(s.id);
  if (msg?.success) message.success(t('pages.naive.toasts.started'));
}
async function onStop(s) {
  const msg = await stop(s.id);
  if (msg?.success) message.success(t('pages.naive.toasts.stopped'));
}
const logOpen = ref(false);
const logTarget = ref(null);
const logText = ref('');
const logLoading = ref(false);

async function onShowLog(srv) {
  logTarget.value = srv;
  logOpen.value = true;
  await reloadLog();
}

async function reloadLog() {
  if (!logTarget.value) return;
  logLoading.value = true;
  try {
    const res = await fetchLog(logTarget.value.id, 200);
    if (res?.success) {
      logText.value = res.obj || '';
    } else {
      logText.value = res?.msg || t('pages.naive.logError');
    }
  } finally {
    logLoading.value = false;
  }
}

async function onRestart(s) {
  const msg = await restart(s.id);
  if (msg?.success) message.success(t('pages.naive.toasts.restarted'));
}

async function onResetTraffic(s) {
  const msg = await resetTraffic(s.id);
  if (msg?.success) message.success(t('pages.naive.toasts.trafficReset'));
}

function urlFor(s, user, pass) {
  return `naive+https://${encodeURIComponent(user)}:${encodeURIComponent(pass)}@${s.domain}:${s.port}`;
}

function clientUrl(s) {
  return urlFor(s, s.authUser, s.authPass);
}

// All shareable credentials for a server: the primary auth plus every enabled
// extra user. Each becomes its own copy target / QR.
function credsFor(s) {
  const list = [{ label: s.authUser, url: urlFor(s, s.authUser, s.authPass) }];
  for (const u of s.users || []) {
    if (u.enable && u.username) {
      list.push({ label: u.username, url: urlFor(s, u.username, u.password) });
    }
  }
  return list;
}

async function onCopy(s) {
  await ClipboardManager.write(clientUrl(s));
  message.success(t('copied'));
}

const qrOpen = ref(false);
const qrTarget = ref(null);

const qrCreds = computed(() => (qrTarget.value ? credsFor(qrTarget.value) : []));

function onShowQr(s) {
  qrTarget.value = s;
  qrOpen.value = true;
}

function isRunning(id) {
  return !!statuses.value[id]?.running;
}

function isDepleted(s) {
  return s.total > 0 && (s.up || 0) + (s.down || 0) >= s.total;
}

function isExpired(s) {
  return s.expiryTime > 0 && Date.now() >= s.expiryTime;
}

const totals = computed(() => {
  const list = servers.value;
  let running = 0;
  for (const s of list) if (statuses.value[s.id]?.running) running += 1;
  return {
    total: list.length,
    running,
    stopped: Math.max(0, list.length - running),
  };
});

const columns = computed(() => [
  { key: 'remark', title: t('pages.naive.fields.remark'), dataIndex: 'remark' },
  { key: 'domain', title: t('pages.naive.fields.domain') },
  { key: 'enable', title: t('pages.naive.fields.enable'), width: 110 },
  { key: 'status', title: t('pages.naive.statusCol'), width: 120 },
  { key: 'traffic', title: t('pages.naive.trafficCol'), width: 150 },
  { key: 'actions', title: '', width: 340, align: 'right' },
]);
</script>

<template>
  <a-config-provider :theme="antdThemeConfig">
    <a-layout class="naive-page" :class="{ 'is-dark': themeState.isDark, 'is-ultra': themeState.isUltra }">
      <AppSidebar :base-path="basePath" :request-uri="requestUri" />

      <a-layout class="content-shell">
        <a-layout-content id="content-layout" class="content-area">
          <a-spin :spinning="!fetched" :delay="200" tip="Loading…" size="large">
            <div v-if="!fetched" class="loading-spacer" />

            <a-row v-else :gutter="[isMobile ? 8 : 16, isMobile ? 8 : 12]">
              <!-- caddy install banner -->
              <a-col v-if="!caddy.installed" :span="24">
                <a-alert
                  type="warning"
                  show-icon
                  :message="t('pages.naive.caddy.missingTitle')"
                  :description="caddy.goPresent ? t('pages.naive.caddy.canInstall') : t('pages.naive.caddy.noGo')"
                >
                  <template #action>
                    <a-button
                      v-if="caddy.goPresent"
                      size="small"
                      type="primary"
                      :loading="installing"
                      @click="onInstallCaddy"
                    >
                      {{ installing ? t('pages.naive.caddy.installing') : t('pages.naive.caddy.install') }}
                    </a-button>
                  </template>
                </a-alert>
              </a-col>
              <a-col v-if="installing || installLog" :span="24">
                <a-card size="small">
                  <pre class="install-log">{{ installLog || '...' }}</pre>
                </a-card>
              </a-col>

              <a-col v-if="caddy.installed" :span="24">
                <a-alert
                  type="success"
                  show-icon
                  :message="t('pages.naive.caddy.installedTitle', { v: caddy.version || '?' })"
                  :description="`${caddy.source}: ${caddy.path}`"
                  closable
                />
              </a-col>

              <!-- summary -->
              <a-col :span="24">
                <a-card size="small" hoverable class="summary-card">
                  <a-row :gutter="[16, isMobile ? 16 : 12]">
                    <a-col :xs="8" :sm="8" :md="8">
                      <CustomStatistic :title="t('pages.naive.totals.total')" :value="String(totals.total)">
                        <template #prefix>
                          <CloudServerOutlined />
                        </template>
                      </CustomStatistic>
                    </a-col>
                    <a-col :xs="8" :sm="8" :md="8">
                      <CustomStatistic :title="t('pages.naive.totals.running')" :value="String(totals.running)">
                        <template #prefix>
                          <CheckCircleOutlined style="color: #52c41a" />
                        </template>
                      </CustomStatistic>
                    </a-col>
                    <a-col :xs="8" :sm="8" :md="8">
                      <CustomStatistic :title="t('pages.naive.totals.stopped')" :value="String(totals.stopped)">
                        <template #prefix>
                          <CloseCircleOutlined style="color: #ff4d4f" />
                        </template>
                      </CustomStatistic>
                    </a-col>
                  </a-row>
                </a-card>
              </a-col>

              <!-- table -->
              <a-col :span="24">
                <a-card size="small" hoverable class="list-card">
                  <template #title>
                    <span>{{ t('pages.naive.title') }}</span>
                  </template>
                  <template #extra>
                    <a-space>
                      <a-button :loading="loading" @click="refresh">
                        <template #icon><ReloadOutlined /></template>
                        {{ t('refresh') }}
                      </a-button>
                      <a-button type="primary" @click="onAdd">
                        <template #icon><PlusOutlined /></template>
                        {{ t('pages.naive.add') }}
                      </a-button>
                    </a-space>
                  </template>

                  <!-- mobile card stack -->
                  <div v-if="isMobile" class="mobile-cards">
                    <div v-if="servers.length === 0" class="card-empty">
                      <a-empty :description="t('pages.naive.empty')" />
                    </div>
                    <div v-for="srv in servers" :key="srv.id" class="srv-card">
                      <div class="srv-head">
                        <div class="srv-title">{{ srv.remark || `naive-${srv.id}` }}</div>
                        <a-tag
                          v-if="isRunning(srv.id) && statuses[srv.id]?.listening && statuses[srv.id]?.responding"
                          color="success"
                        >{{ t('pages.naive.running') }}</a-tag>
                        <a-tag
                          v-else-if="isRunning(srv.id) && statuses[srv.id]?.listening"
                          color="warning"
                        >{{ t('pages.naive.unresponsive') }}</a-tag>
                        <a-tag v-else-if="isRunning(srv.id)" color="processing">{{ t('pages.naive.starting') }}</a-tag>
                        <a-tag v-else color="default">{{ t('pages.naive.stopped') }}</a-tag>
                        <a-tag v-if="isExpired(srv)" color="error">{{ t('pages.naive.expired') }}</a-tag>
                        <a-tag v-else-if="isDepleted(srv)" color="error">{{ t('pages.naive.depleted') }}</a-tag>
                      </div>
                      <div class="srv-row">
                        <span class="srv-label">Endpoint</span>
                        <code>{{ srv.domain }}:{{ srv.port }}</code>
                      </div>
                      <div class="srv-row">
                        <span class="srv-label">{{ t('pages.naive.fields.enable') }}</span>
                        <a-tag :color="srv.enable ? 'green' : 'default'" :bordered="false">
                          {{ srv.enable ? t('pages.naive.enabled') : t('pages.naive.disabled') }}
                        </a-tag>
                      </div>
                      <a-space :size="6" wrap class="srv-actions">
                        <a-button size="small" @click="onCopy(srv)">
                          <template #icon><CopyOutlined /></template>
                        </a-button>
                        <a-button size="small" @click="onShowQr(srv)">
                          <template #icon><QrcodeOutlined /></template>
                        </a-button>
                        <a-button
                          v-if="!isRunning(srv.id)"
                          size="small"
                          type="primary"
                          @click="onStart(srv)"
                        >
                          <template #icon><PlayCircleOutlined /></template>
                          {{ t('pages.naive.start') }}
                        </a-button>
                        <a-button v-else size="small" danger @click="onStop(srv)">
                          <template #icon><PauseCircleOutlined /></template>
                          {{ t('pages.naive.stop') }}
                        </a-button>
                        <a-button size="small" :disabled="!isRunning(srv.id)" @click="onRestart(srv)">
                          <template #icon><ReloadOutlined /></template>
                        </a-button>
                        <a-button size="small" @click="onShowLog(srv)">
                          <template #icon><FileTextOutlined /></template>
                        </a-button>
                        <a-button size="small" @click="onEdit(srv)">
                          <template #icon><EditOutlined /></template>
                        </a-button>
                        <a-button size="small" danger @click="onDelete(srv)">
                          <template #icon><DeleteOutlined /></template>
                        </a-button>
                      </a-space>
                    </div>
                  </div>

                  <!-- desktop table -->
                  <a-table
                    v-else
                    :columns="columns"
                    :data-source="servers"
                    :pagination="false"
                    :row-key="(r) => r.id"
                    :size="isMobile ? 'small' : 'middle'"
                    :scroll="{ x: 'max-content' }"
                  >
                    <template #bodyCell="{ column, record }">
                      <template v-if="column.key === 'remark'">
                        {{ record.remark || `naive-${record.id}` }}
                      </template>

                      <template v-else-if="column.key === 'domain'">
                        <code>{{ record.domain }}:{{ record.port }}</code>
                      </template>

                      <template v-else-if="column.key === 'enable'">
                        <a-tag :color="record.enable ? 'green' : 'default'">
                          {{ record.enable ? t('pages.naive.enabled') : t('pages.naive.disabled') }}
                        </a-tag>
                      </template>

                      <template v-else-if="column.key === 'status'">
                        <a-tag
                          v-if="isRunning(record.id) && statuses[record.id]?.listening && statuses[record.id]?.responding"
                          color="success"
                        >
                          {{ t('pages.naive.running') }}
                        </a-tag>
                        <a-tag
                          v-else-if="isRunning(record.id) && statuses[record.id]?.listening"
                          color="warning"
                        >
                          {{ t('pages.naive.unresponsive') }}
                        </a-tag>
                        <a-tag v-else-if="isRunning(record.id)" color="processing">
                          {{ t('pages.naive.starting') }}
                        </a-tag>
                        <a-tag v-else color="default">{{ t('pages.naive.stopped') }}</a-tag>
                        <a-tag v-if="isExpired(record)" color="error">{{ t('pages.naive.expired') }}</a-tag>
                        <a-tag v-else-if="isDepleted(record)" color="error">{{ t('pages.naive.depleted') }}</a-tag>
                      </template>

                      <template v-else-if="column.key === 'traffic'">
                        <a-tooltip :title="t('pages.naive.trafficHint')">
                          <span>↑ {{ SizeFormatter.sizeFormat(record.up || 0) }} / ↓ {{ SizeFormatter.sizeFormat(record.down || 0) }}</span>
                        </a-tooltip>
                      </template>

                      <template v-else-if="column.key === 'actions'">
                        <a-space :size="4" wrap>
                          <a-tooltip :title="t('pages.naive.copyUrl')">
                            <a-button size="small" @click="onCopy(record)">
                              <template #icon><CopyOutlined /></template>
                            </a-button>
                          </a-tooltip>
                          <a-tooltip :title="t('pages.naive.showQr')">
                            <a-button size="small" @click="onShowQr(record)">
                              <template #icon><QrcodeOutlined /></template>
                            </a-button>
                          </a-tooltip>
                          <a-button
                            v-if="!isRunning(record.id)"
                            size="small"
                            type="primary"
                            @click="onStart(record)"
                          >
                            <template #icon><PlayCircleOutlined /></template>
                            {{ t('pages.naive.start') }}
                          </a-button>
                          <a-button v-else size="small" danger @click="onStop(record)">
                            <template #icon><PauseCircleOutlined /></template>
                            {{ t('pages.naive.stop') }}
                          </a-button>
                          <a-tooltip :title="t('pages.naive.restart')">
                            <a-button size="small" :disabled="!isRunning(record.id)" @click="onRestart(record)">
                              <template #icon><ReloadOutlined /></template>
                            </a-button>
                          </a-tooltip>
                          <a-tooltip :title="t('pages.naive.viewLog')">
                            <a-button size="small" @click="onShowLog(record)">
                              <template #icon><FileTextOutlined /></template>
                            </a-button>
                          </a-tooltip>
                          <a-button size="small" @click="onEdit(record)">
                            <template #icon><EditOutlined /></template>
                          </a-button>
                          <a-tooltip :title="t('pages.naive.resetTraffic')">
                            <a-button size="small" @click="onResetTraffic(record)">
                              <template #icon><ReloadOutlined /></template>
                            </a-button>
                          </a-tooltip>
                          <a-button size="small" danger @click="onDelete(record)">
                            <template #icon><DeleteOutlined /></template>
                          </a-button>
                        </a-space>
                      </template>
                    </template>

                    <template #emptyText>
                      <a-empty :description="t('pages.naive.empty')" />
                    </template>
                  </a-table>
                </a-card>
              </a-col>
            </a-row>
          </a-spin>
        </a-layout-content>
      </a-layout>

      <NaiveFormModal
        v-model:open="formOpen"
        :mode="formMode"
        :server="formServer"
        @save="onSave"
      />

      <a-modal
        v-model:open="logOpen"
        :title="t('pages.naive.logTitle', { name: logTarget?.remark || `naive-${logTarget?.id}` })"
        width="780px"
        :footer="null"
      >
        <a-space style="margin-bottom: 8px;">
          <a-button :loading="logLoading" size="small" @click="reloadLog">
            <template #icon><ReloadOutlined /></template>
            {{ t('refresh') }}
          </a-button>
          <span class="log-hint">{{ t('pages.naive.logHint') }}</span>
        </a-space>
        <pre class="log-view">{{ logText || t('pages.naive.logEmpty') }}</pre>
      </a-modal>

      <a-modal
        v-model:open="qrOpen"
        :title="t('pages.naive.qrTitle', { name: qrTarget?.remark || `naive-${qrTarget?.id}` })"
        width="420px"
        :footer="null"
      >
        <QrPanel
          v-for="cred in qrCreds"
          :key="cred.label"
          :value="cred.url"
          :remark="cred.label"
        />
      </a-modal>
    </a-layout>
  </a-config-provider>
</template>

<style scoped>
.naive-page {
  --bg-page: #e6e8ec;
  --bg-card: #ffffff;

  min-height: 100vh;
  background: var(--bg-page);
}

.naive-page.is-dark {
  --bg-page: #1e1e1e;
  --bg-card: #252526;
}

.naive-page.is-dark.is-ultra {
  --bg-page: #050505;
  --bg-card: #0c0e12;
}

.naive-page :deep(.ant-layout),
.naive-page :deep(.ant-layout-content) {
  background: transparent;
}

.content-shell {
  background: transparent;
}

.content-area {
  padding: 24px;
}

@media (max-width: 768px) {
  .content-area {
    padding: 8px;
  }
}

.loading-spacer {
  min-height: calc(100vh - 120px);
}

.summary-card {
  padding: 16px;
}

@media (max-width: 768px) {
  .summary-card {
    padding: 8px;
  }
}

.list-card code {
  font-size: 12px;
}

.install-log {
  max-height: 240px;
  overflow: auto;
  font-size: 11px;
  white-space: pre-wrap;
  margin: 0;
}

/* mobile card stack — mirrors the nodes/inbounds responsive pattern */
.mobile-cards {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.card-empty {
  padding: 16px 0;
}

.srv-card {
  border: 1px solid rgba(0, 0, 0, 0.06);
  border-radius: 6px;
  padding: 10px 12px;
  background: var(--bg-card);
}

.naive-page.is-dark .srv-card {
  border-color: rgba(255, 255, 255, 0.08);
}

.srv-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 6px;
}

.srv-title {
  font-weight: 600;
  font-size: 14px;
  margin-right: 8px;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.srv-row {
  display: flex;
  justify-content: space-between;
  font-size: 12px;
  padding: 2px 0;
  gap: 12px;
}

.srv-row code {
  font-size: 12px;
  color: inherit;
}

.srv-label {
  opacity: 0.65;
}

.srv-actions {
  margin-top: 8px;
}

.log-view {
  max-height: 480px;
  overflow: auto;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 12px;
  line-height: 1.4;
  background: rgba(0, 0, 0, 0.04);
  padding: 10px 12px;
  border-radius: 4px;
  margin: 0;
  white-space: pre-wrap;
  word-break: break-all;
}

.naive-page.is-dark .log-view {
  background: rgba(255, 255, 255, 0.06);
}

.log-hint {
  font-size: 11px;
  opacity: 0.6;
}
</style>
